### ISSUE TITLE
want the `extractProblems` command to be independent

### ISSUE THREAD

**Issue by Seasawher** [dwrensha/compfiles#13]
Hello. The command in this repository to extract answers from a problem is nice. I've been thinking of making a collection of questions in Lean too, but...

* Including the answers in the source would immediately spoil it.
* If I don't include the answers in the source, I can't automatically check whether the problem is correct or not.

I was troubled by this dilemma. Your command solves my problem.

Can you release just the `extractProblems` command as a separate package? I don't want to import the whole `compfiles` just to use the `extractProblems` command.

Thank you.

**Comment by dwrensha** [comment]
Thanks for the suggestion. I might end up doing this. Until then you should feel welcome to copy the code from `ProblemExtraction.lean` and adapt it to your own purposes. It's all licensed under the Apache 2 license.

**Comment by Seasawher** [comment]
Thanks for your reply.

I have rethought the functionality that a tool should have to achieve my goal, and have created the following tool myself.

https://github.com/Seasawher/mk-exercise
